### ISSUE TITLE
README needs an "I told you so"

### ISSUE THREAD

**Issue by jayvdb** [tomoconnor/oracle-java7-installer#1]
> Also, Oracle will probably cripple the webupd8 method at some point, probably by putting a captcha in front of the downloads page. Wouldn't surprise me.

**Comment by jayvdb** [comment]
And maybe re-do it for java8 using http://dl.bintray.com/walkingdevs/mirrors/

**Comment by tomoconnor** [comment]
I just realised this repo is 7 years old.  If you wanna fix it, I'll accept a pull request, but really openjdk is a lot better than it used to be, and I don't even remember how this works :laughing:

**Comment by jayvdb** [comment]
I was googling around for an easy solution for Travis CI dropping support for oracle jdk.  I only care about Oracle JDK 8 (and maybe 7) due to supporting old apps.  Not enough care factor to revive this project, I think.  Maybe best to just let it die, as you are right that OpenJDK 7/8 are very good.  But I couldnt help but chuckle that 7 years ago you locked in a commit predicting this day.

**Comment by tomoconnor** [comment]
Can you find a docker image with the right Oracle JDK8 in it, then run your apps in that? :fearful:

**Comment by jayvdb** [comment]
I have one of those, and have been adding layers on top.  Anyways, neither of us have enough interest to revive this, so I'll close for now.
